CREATE TABLE User (
  email VARCHAR(255) UNIQUE NOT NULL,
  facebookId VARCHAR(255) UNIQUE NOT NULL,
  firstName VARCHAR(255) NOT NULL,
  lastName VARCHAR(255) NOT NULL,
  id INTEGER PRIMARY KEY AUTO_INCREMENT NOT NULL
);
CREATE TABLE Post (
  authorId INTEGER NOT NULL,
  content MEDIUMTEXT,
  createdAt TIMESTAMP NOT NULL DEFAULT now(),
  id INTEGER PRIMARY KEY AUTO_INCREMENT NOT NULL,
  published BOOLEAN NOT NULL DEFAULT false,
  title VARCHAR(255) NOT NULL,
  updatedAt TIMESTAMP,

  FOREIGN KEY (authorId) REFERENCES User(id)
);
CREATE TABLE Profile (
  bio TINYTEXT,
  id INTEGER PRIMARY KEY AUTO_INCREMENT NOT NULL,
  userId INTEGER UNIQUE NOT NULL,
  
  FOREIGN KEY (userId) REFERENCES User(id)
)